### ISSUE TITLE
Seeking Clarity on "None" info in output file

### ISSUE THREAD

**Issue by Mkddb** [Illumina/SMNCopyNumberCaller#5]
Hello Team,

First of all, Thanks for creating this wonderful tool. it's really easy and straightforward to run, giving the output in a meaningful format.

I am a bit confused about "None" info in output columns. 

1) say it's "None" for a sample in "isCarrier". Does this really mean there was no call for this sample or the tool could not fetch the reads for it? 
2) also for SMN1_CN / SMN2_CN / SMN2delta7-8_CN / g.27134T>G_CN columns, what does "None" means?  
3) Moreover, there are samples for which the later 2-4 columns show "None". and the "isCarrier" status is "False". 
4) Last, I want to calculate the allele frequency for carriers. Do i need to include the samples with "None" status in "isCarrier" column for the total allele count? also, do i need to include the samples with "None" status in "isCarrier" and "None" status in "isSMA" columns for the total allele count. or these samples must be excluded as there were "No calls" for such samples?

![Screenshot from 2021-07-13 11-03-22](https://user-images.githubusercontent.com/61584787/125396498-44141d80-e3ca-11eb-8c70-982d5b422727.png)

can you please clarify these points?

With kind regards,
Mkd

**Comment by xiao-chen-xc** [comment]
Hi Mkd,

Glad to learn that our tool is useful for you.

"None" means a no-call. The caller starts by calling the summed copy number (CN) of SMN1 and SMN2 and then differentiates SMN1 from SMN2 based on differentiating sites. If the summed CN is a no-call, e.g. we cannot tell if the summed CN is 3 or 4, then the downstream steps would be affected and produce no-calls, see below.

1. SMN2delta7-8_CN is inferred from the summed CN in exon7-8 and exon1-6, so it is a no-call when either of those two values is a no-call.
2. SMN1_CN and SMN2_CN are called based on the summed CN in exon7-8 and read counts at differentiating sites. If the summed CN is a no-call, then SMN1/SMN2 CN would be a no-call. Alternatively, if the read counts are ambiguous so that we cannot confidently differentiate SMN1 from SMN2, we could get a no-call too.
3. g.27134T>G_CN is called from the summed CN in exon7-8 and read counts at this site, so a no-call could be made if there is ambiguity in either.
4. For the isCarrier value, it's possible that SMN1_CN is a no-call, but the ambiguity is, for example, between 2 and 3, then we know that the sample is not a carrier (i.e. SMN1_CN is not equal to 1) and isCarrier could be confidently set to False.

If you would like to get some information on why a no-call is made for a specific sample, you can try using our visualization tool. 

For allele frequency calculation, I would recommend excluding the no-calls in the total count. No-calls are with respect to a specific value - for example, a sample can be a no-call for SMN2delta7-8_CN but its SMN1_CN and SMN2_CN calls are still reliable. If you want to calculate copy number frequencies, you could use the SMN1_CN column and SMN2_CN column. For carrier rate calculation there are two ways. You can either use the isCarrier column or the SMN1_CN column. The difference would just be a very small number of samples where SMN1_CN is None but isCarrier is False and this difference would be very minimal.

Hope this helps and let me know if there is anything that's not clear.

Thanks,
Xiao

**Comment by Mkddb** [comment]
Hello Xiao,

That's really nice explanation. 
I got all your points. Thanks for the recommendation for allele frequency calculation. 

I am getting another error for certain samples. It would be really helpful if you can help me with that.

I was following a similar command line to the default on the Hg38 build. Most of the samples run smoothly as expected.  A few samples threw this same error. 

Traceback (most recent call last):
  File "/mnt/dragen/Resources/tool/SMNCopyNumberCaller-master/smn_caller.py", line 298, in <module>
    main()
  File "/mnt/dragen/Resources/tool/SMNCopyNumberCaller-master/smn_caller.py", line 267, in main
    smn_call = smn_cn_caller(
  File "/mnt/dragen/Resources/tool/SMNCopyNumberCaller-master/smn_caller.py", line 149, in smn_cn_caller
    final_call = get_smn12_call(
  File "/mnt/dragen/Resources/tool/SMNCopyNumberCaller-master/caller/call_smn12.py", line 285, in get_smn12_call
    tag, cn_smn1, lsitecall_loose = get_smn1_call_and_tag(cn_prob, combined_call)
  File "/mnt/dragen/Resources/tool/SMNCopyNumberCaller-master/caller/call_smn12.py", line 153, in get_smn1_call_and_tag
    if lsitecall_medium_counter[0][1] >= 5:

It appear if "none of the SMN copy details" for these samples could be fetched and can be considered as failed samples. 

Can you please look into it and suggest accordingly?

Thanks,
Mkd

**Comment by xiao-chen-xc** [comment]
Hi Mkd,

I made a small code change to the master branch. It might fix the error in your data. I'm guessing those samples that had the error all had low data quality and they will remain no-calls even if the program runs without error. You could check if those samples have quality issues like low coverage. 

Thanks,
Xiao

**Comment by Mkddb** [comment]
Hello Xiao,

Thanks for the prompt responses.
I will check their data quality and coverage. Also, rerunning the program with fresh code changes.
Probably yes, I might see No calls for these samples, even in output.
I will get back to you with the results.

Thanks again,
Mkd

**Comment by Mkddb** [comment]
Hello Xiao, 

That code change was able to handle those samples and didn't give any more errors. 
Yes, these samples have low coverages and reported "None" for SMN1_CN and SMN2_CN and "False" for "isSMA" and "isCareer". Few of those samples (Coverage<10X) had "None" for "isSMA" and "isCareer" columns themselves. 

Once again, 
Thanks a lot for building this useful tool and for the entire help and recommendations.

With Kinds regards,
Mkd

**Comment by xiao-chen-xc** [comment]
No problem!
